repo: https://github.com/burhanuguz/advanced-argocd-gitops.git
plugin: 'argocd-vault-plugin'
argoProject: 'default'
syncOrder: '0'
branch: 'master'
namespace: 'app-2-namespace'
appName: 'app-2-namespace'