apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://github.com/burhanuguz/advanced-argocd-gitops.git
        revision: HEAD
        files:
          - path: 'clusters/*/*/Application.yaml'
  template:
    metadata:
      name: '{{ index .path.segments 1 }}-{{ .appName }}'
      namespace: argo-cd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncOrder }}'
        argocd.argoproj.io/manifest-generate-paths: '.'
      labels:
        clustername: '{{ index .path.segments 1 }}'
        app: '{{ default "" .chartName }}'
    spec:
      syncPolicy:
        syncOptions:
        - ServerSideApply=true
      #   automated: {}
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: '{{ .namespace }}'
      project: '{{ .argoProject }}'
      source:
        repoURL: '{{ .repo }}'
        targetRevision: '{{ .branch }}'
        path: '{{ .path.path }}'
        plugin:
          env:
            - name: pluginName
              value: '{{ .plugin }}'
            - name: AVP_SECRET
              value: '{{ default "" .keyVault }}'
            # These values are needed when both local and remote helm plugin is used
            - name: chartName
              value: '{{ default "" .chartName }}'
            - name: chartReleaseName
              value: '{{ default "" .appName | trunc 53 }}'
            ## chartRepository and chartVersion values are needed when helm remote plugin is used
            - name: chartRepository
              value: '{{ default "" .chartRepository }}'
            - name: chartVersion
              value: '{{ default "" .chartVersion }}'
            ## You can put extra args with spaces.
            - name: extraArgs
              value: '{{ default "" .extraArgs }}'