apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: '/ApplicationSet.yaml'
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - Replace=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/burhanuguz/advanced-argocd-gitops.git
    targetRevision: HEAD
    directory:
      include: 'ApplicationSet.yaml'
