apiVersion: v1
kind: LimitRange
metadata:
  name: app-1-limitrange
  namespace: app-1-namespace
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 900Mi
      defaultRequest:
        cpu: 100m
        memory: 600Mi
      max:
        cpu: 1
        memory: 2100Mi